Fixed multitype list
AtsushiSakai/PythonRobotics pull request #1076
Opened 2024-09-12 13:39 UTC by AryazE

#### Reference issue

#### What does this implement/fix?
This PR ensures that the lists provided to some path planning algorithms are all `int`s and not a mix of `float` and `int`.

#### Additional information

#### CheckList
- [ ] Did you add an unittest for your new example or defect fix?
- [ ] Did you add documents for your new example?
- [ ] All CIs are green? (You can check it after submitting)

2024-10-15 10:11 UTC, shravankumar-12 commented
thankyou

2024-12-21 06:17 UTC, AtsushiSakai approved these changes
LGTM. Thanks!!

2024-12-21 10:35 UTC, AtsushiSakai requested changes
Sorry, I think some changes should be rollbacked. PTAL. @AryazE

2024-12-21 10:35 UTC, AtsushiSakai commented on PathPlanning/BreadthFirstSearch/breadth_first_search.py
> -    sx = 10.0  # [m]
sorry, we can keep these float parameters as before.

2024-12-21 10:35 UTC, AtsushiSakai commented on PathPlanning/BreadthFirstSearch/breadth_first_search.py
> -        ox.append(40.0)
sorry, we can keep these float parameters as before.

2024-12-21 10:35 UTC, AtsushiSakai commented on PathPlanning/Dijkstra/dijkstra.py
> -    grid_size = 2.0  # [m]
sorry, we can keep these float parameters as before.

2024-12-21 10:35 UTC, AtsushiSakai commented on PathPlanning/VoronoiRoadMap/voronoi_road_map.py
> -        ox.append(40.0)
sorry, we can keep these float parameters as before.

2024-12-21 10:35 UTC, AtsushiSakai commented on PathPlanning/VoronoiRoadMap/voronoi_road_map.py
> -    robot_size = 5.0  # [m]
sorry, we can keep these float parameters as before.

2024-12-21 10:35 UTC, AtsushiSakai commented on PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py
> -        oy.append(60.0 - i)
sorry, we can keep these float parameters as before.

2024-12-21 10:35 UTC, AtsushiSakai commented on PathPlanning/ProbabilisticRoadMap/probabilistic_road_map.py
> -    robot_size = 5.0  # [m]
sorry, we can keep these float parameters as before.

2025-01-20 04:25 UTC, AtsushiSakai commented
@AryazE  Is it possible to finish this PR?

2025-01-20 08:07 UTC, AryazE commented
Done! Thanks for your patience.

2025-01-20 08:16 UTC, AtsushiSakai approved these changes
LGTM. Thanks!!

2025-01-20 08:16 UTC, merged