Fix: dead link URL in doc
AtsushiSakai/PythonRobotics pull request #1087
Opened 2024-10-20 04:01 UTC by parmaski

#### Reference issue

none

#### What does this implement/fix?

fix dead (HTTP status 30X or 40X) URL links in documents.

#### Additional information

 - The link shows `This repo has been deactivated`, but no way to fix
   - https://codecov.io/gh/AtsushiSakai/PythonRobotics
 - The sites not explicitly redirected but convinced to be successors
   1. [original](http://www.mpc.berkeley.edu/mpc-course-material/)-> [new site](https://sites.google.com/berkeley.edu/mpc-lab/mpc-course-material)
   1. [original](http://planning.cs.uiuc.edu/node822.html) -> [new site](https://lavalle.pl/planning/node822.html)
 - new sites not found, then redirected to Wayback Machine because helpful to understand the algorithms
   - https://web.archive.org/web/20200130224918/http://doswa.com/2009/07/13/circle-segment-intersectioncollision.html
   - https://web.archive.org/web/20201103052224/https://sites.google.com/site/ece452bugalgorithms/
 - new sites not found but unfixed links because just educational course introductions
   - http://cobweb.cs.uga.edu/~ramviyas/csci_x530.html
   - https://courses.cit.ie/index.cfm/page/module/moduleId/14416

#### CheckList
- [ ] Did you add an unittest for your new example or defect fix?
- [ ] Did you add documents for your new example?
- [ ] All CIs are green? (You can check it after submitting)

2024-10-20 05:30 UTC, parmaski commented
On [CI](https://ci.appveyor.com/project/AtsushiSakai/pythonrobotics/builds/50829326), ruff reports errors on the lines where I made no change.
I beg to leave these lines irresponsible for me as it is.

2024-12-21 10:46 UTC, AtsushiSakai requested changes
Thank you so much for this great clean up PR.

For these links, could you please remove these link?

> The link shows This repo has been deactivated, but no way to fix
> https://codecov.io/gh/AtsushiSakai/PythonRobotics
> new sites not found but unfixed links because just educational course introductions
> http://cobweb.cs.uga.edu/~ramviyas/csci_x530.html
> https://courses.cit.ie/index.cfm/page/module/moduleId/14416

2024-12-26 02:03 UTC, parmaski commented
@AtsushiSakai I've fixed. 
Since no educational users are left, I've also modified the description.

2025-01-20 04:28 UTC, AtsushiSakai commented
Let me close once to rerun CI.

2025-01-24 04:28 UTC, AtsushiSakai approved these changes
Fix the CI errors by #1124, let's merge this. Thanks @parmaski

2025-01-24 04:28 UTC, merged