Extend frenet_optimal_trajectory to support more scenarios
AtsushiSakai/PythonRobotics pull request #1114
Opened 2024-12-24 13:08 UTC by Aglargil

#### Reference issue
fix #1073

#### What does this implement/fix?

- Add `CartesianFrenetConverter`: A class for converting states between Cartesian and Frenet coordinate systems
- Add third derivative and curvature rate calculations to `CubicSpline`
- Add LowSpeed/HighSpeed `LateralMovementStrategy`, add MergingAndStopping/VelocityKeeping `LongitudinalMovementStrategy`
- Fix : `s_d` was used as the acceleration, but since` s_d` only represents the longitudinal acceleration, the `CartesianFrenetConverter` is now used to compute the acceleration `a` consistently

#### Additional information
- Since I’m unsure which formatting tool to use, I used ruff as mentioned in [this link](https://atsushisakai.github.io/PythonRobotics/getting_started.html#requirements). If there’s a standard formatting method for the project, please let me know, and I’ll update it right away.

#### CheckList
- [x] Did you add an unittest for your new example or defect fix?
- [x] Did you add documents for your new example? (Already have)
- [x] All CIs are green? (You can check it after submitting)

2025-01-20 04:36 UTC, AtsushiSakai requested changes
Thank you for your PR and sorry for late review.
I have some comments, PTAL.

And I will be very happy if you can update this doc to explain this algorithm and simulations:
https://github.com/AtsushiSakai/PythonRobotics/blob/master/docs/modules/path_planning/frenet_frame_path/frenet_frame_path_main.rst

2025-01-20 04:36 UTC, AtsushiSakai commented on PathPlanning/CubicSpline/cubic_spline_planner.py
> +
Is it possbile to add the `Parameter` section?

2025-01-20 04:36 UTC, AtsushiSakai commented on PathPlanning/FrenetOptimalTrajectory/cartesian_frenet_converter.py
> +        d = math.copysign(math.sqrt(dx * dx + dy * dy), cross_rd_nd)
We can use `math.hypot` here.

2025-01-20 04:36 UTC, AtsushiSakai commented on PathPlanning/FrenetOptimalTrajectory/frenet_optimal_trajectory.py
>              plt.plot(path.x[1:], path.y[1:], "-or")
These comment out lines are needed?

2025-01-20 06:09 UTC, Aglargil commented
> @Aglargil Thank you for your PR and sorry for late review.@Aglargil 感谢您的公关，并对迟到的评论表示歉意。 I have some comments, PTAL.我有一些意见，PTAL。
> 
> And I will be very happy if you can update this doc to explain this algorithm and simulations: https://github.com/AtsushiSakai/PythonRobotics/blob/master/docs/modules/path_planning/frenet_frame_path/frenet_frame_path_main.rst

Thank you for your reply, I will address the comments within a day!

2025-01-21 01:58 UTC, Aglargil commented
@AtsushiSakai I've updated it, so if there are any other suggestions, please alert me and I'll get right on it!

2025-01-21 08:38 UTC, AtsushiSakai requested changes

2025-01-21 08:38 UTC, AtsushiSakai commented on docs/modules/path_planning/frenet_frame_path/frenet_frame_path_main.rst
> +
Please create a PR for GIF files in this dedicated GIF repository 
https://github.com/AtsushiSakai/PythonRoboticsGifs
instead of the main repository and use the link from there.
This is to keep the size of the main repository small.

2025-01-21 08:38 UTC, AtsushiSakai commented on PathPlanning/FrenetOptimalTrajectory/frenet_optimal_trajectory.py
> +    HighSpeed = auto()
Please use Capital names for enum.

2025-01-21 08:38 UTC, AtsushiSakai commented on PathPlanning/FrenetOptimalTrajectory/frenet_optimal_trajectory.py
> +    MergingAndStopping = auto()
Please use Capital names for enum.

2025-01-21 09:46 UTC, Aglargil commented on docs/modules/path_planning/frenet_frame_path/frenet_frame_path_main.rst
> +
I have already submitted the GIF files to the dedicated GIF repository as per your suggestion. Here is the link to the pull request: [PR #4](https://github.com/AtsushiSakai/PythonRoboticsGifs/pull/4).

I really appreciate this approach to keep the main repository size small. It's a great learning for me on how to manage project resources efficiently. Thank you for guiding me on this!

2025-01-21 10:18 UTC, AtsushiSakai requested changes

2025-01-22 02:43 UTC, Aglargil commented on PathPlanning/FrenetOptimalTrajectory/cartesian_frenet_converter.py
> +
The detailed mathematical derivation is already available in the appendix of the paper, so I think it might not be necessary to include it in the documentation.
![image](https://github.com/user-attachments/assets/a019a393-4593-4702-8160-cbc0e137825a)

2025-01-22 09:50 UTC, AtsushiSakai approved these changes
LGTM. Than you!!

2025-01-22 09:57 UTC, merged