Create bug.py
AtsushiSakai/PythonRobotics pull request #378
Opened 2020-08-18 06:13 UTC by sarimmehdi

Implemented bug 0, bug 1 and bug 2 planning algorithms

2020-08-29 03:59 UTC, AtsushiSakai commented
@sarimmehdi Hi. Thank you for your interesting PR!. Before core review, could you please add a test file for it? 
This test code might help you:
https://github.com/AtsushiSakai/PythonRobotics/blob/master/tests/test_a_star.py

2020-08-29 06:09 UTC, sarimmehdi commented
@AtsushiSakai I have added the required file, please have a look. Thanks!

2020-08-29 07:12 UTC, AtsushiSakai requested changes

2020-08-29 07:12 UTC, AtsushiSakai commented on PathPlanning/Bug_Planning/bug.py
> +class Bug():
I think `()` is unnecessary

2020-08-29 07:12 UTC, AtsushiSakai commented on PathPlanning/Bug_Planning/bug.py
> +    def __init__(self, startx, starty, goalx, goaly, obsx, obsy):
variable name convention: could you please all variable should use `_` between words. For example,
startx -> start_x
obsx -> obs_x
Could you please fix all variable names?

2020-08-29 07:12 UTC, AtsushiSakai commented on PathPlanning/Bug_Planning/bug.py
> +    def bug0(self):
What is the difference between bug0 or bug1 or bug2? Could you please add docstring which explains the differences?

2020-08-29 07:12 UTC, AtsushiSakai commented on PathPlanning/Bug_Planning/bug.py
> +class Bug():
The class name should be `BugPlanner`?

2020-08-29 07:12 UTC, AtsushiSakai commented on PathPlanning/Bug_Planning/bug.py
> +"""
Could you please change the directory `Bug_Planning` to `BugPlanning`?

2020-08-29 07:12 UTC, AtsushiSakai commented on PathPlanning/Bug_Planning/bug.py
> +        plt.plot(self.obsx, self.obsy, ".k")
Could you please plotting function calls are covered by `show_animation` like:
https://github.com/AtsushiSakai/PythonRobotics/blob/fa227083372445f0f440b5d5ad878d9201ed7476/PathPlanning/AStar/a_star.py#L87-L93

2020-08-29 08:29 UTC, sarimmehdi commented
@AtsushiSakai I do not understand the codecov/project error I am getting above. Can you please have a look and tell me what I need to do?

2020-08-29 12:20 UTC, AtsushiSakai commented
You don’t need to care about codecov error. Next review is last one. I will merge it after you fixed it.

2020-08-29 12:25 UTC, AtsushiSakai requested changes

2020-08-29 12:25 UTC, AtsushiSakai commented on PathPlanning/BugPlanning/bug.py
> +    def bug0(self):
Docstring usually is under function definition. Please check it 
https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard

2020-08-29 12:25 UTC, AtsushiSakai commented on PathPlanning/BugPlanning/bug.py
> +        cand_x, cand_y = -9999, -9999
If 9999 is invalid number, you should use None or inf instead i think.

2020-08-29 17:43 UTC, sarimmehdi commented
@AtsushiSakai I have implemented the requested changes. Please have a look.

2020-08-30 04:04 UTC, AtsushiSakai commented
LGTM. Thank you!!

2020-08-30 04:04 UTC, merged