Added variants of A*
AtsushiSakai/PythonRobotics pull request #395
Opened 2020-09-04 15:06 UTC by sarimmehdi

Implemented A* with beam search, iterative deepening, and dynamic weighting

2020-09-07 15:59 UTC, sarimmehdi commented
Demo: https://www.youtube.com/watch?v=86ST5PbcuBs

2020-09-12 12:00 UTC, AtsushiSakai requested changes
Thank you for interesting PR. I have some minor comments before deep review. PTAL.

2020-09-14 12:43 UTC, sarimmehdi commented
@AtsushiSakai sorry for the late reply. I have made the requested changes. Please have a look.

2020-09-15 09:14 UTC, sarimmehdi commented
@AtsushiSakai `Build execution time has reached the maximum allowed time for your plan (60 minutes)` I don't know how to deal with this. But everything else seems to be working fine. Please let me know if it is okay with you.

2020-09-18 11:38 UTC, sarimmehdi commented
@AtsushiSakai I think everything is fine now, maybe you can have a look at it.

2020-09-20 04:20 UTC, AtsushiSakai requested changes

2020-09-20 04:20 UTC, AtsushiSakai commented on test_a_star_variants.py
> +import PathPlanning.AStar.a_star_variants as astar
Could you please remove this file? it seems duplicate.

2020-09-20 04:20 UTC, AtsushiSakai commented on PathPlanning/AStar/a_star_variants.py
> +        '''Jump point: Instead of exploring all empty spaces of the
Could you please change ''' to """ ?

2020-09-20 04:20 UTC, AtsushiSakai commented on PathPlanning/AStar/a_star_variants.py
> +        '''Beam search: Maintain an open list of just 30 nodes.
Could you please change ''' to """ ?

2020-09-20 04:21 UTC, AtsushiSakai requested changes
Thank you for fixing. This is the last review. After fixing these, I will merge it. PTAL.

2020-09-20 04:23 UTC, AtsushiSakai commented
I have a question. When I use Jump Point search option, It looks like final path is collided to some obstacles. Is it expected?
<img width="576" alt="SS 2020-09-20 at 13 15 12" src="https://user-images.githubusercontent.com/3813847/93694250-6ccddc80-fb44-11ea-9625-6f92fd9e9268.png">

2020-09-20 07:16 UTC, sarimmehdi commented
@AtsushiSakai I implemented the requested changes. For jump-point I forgot to change the parameter for the smaller map. I apologize for the oversight. This is what the path should look like:

Zoomed-out (it might seem like the path is crossing the obstacle but once you zoom in, you see that is not the case):
![jump_point_zoomed_out](https://user-images.githubusercontent.com/36595832/93705920-d2f53800-fb21-11ea-8579-eec6dbbb9985.png)

Zoomed-in (no path crosses the obstacle):
![jump_point](https://user-images.githubusercontent.com/36595832/93705895-86116180-fb21-11ea-8f6c-3cffb0eb0da2.png)

2020-09-21 04:32 UTC, AtsushiSakai approved these changes
LGTM. Thank you so much for great PR!.

2020-09-21 04:32 UTC, merged