Implemented Flowfield Pathfinding
AtsushiSakai/PythonRobotics pull request #408
Opened 2020-09-27 00:40 UTC by sarimmehdi

This algorithm is used in real-time strategy games to do unit pathfinding.

2020-09-27 04:44 UTC, AtsushiSakai requested changes
Thank you for interesting PR. I have some comments. PTAL.

2020-09-27 04:44 UTC, AtsushiSakai commented on PathPlanning/FlowField/flowfield.py
> +        self.cost_field = {}
This field should be initialized in the __init__()

2020-09-27 04:44 UTC, AtsushiSakai commented on PathPlanning/FlowField/flowfield.py
> +        self.vector_field = {}
This field should be initialized in the __init__()

2020-09-27 04:44 UTC, AtsushiSakai commented on PathPlanning/FlowField/flowfield.py
> +        self.integration_field = {}
This field should be initialized in the __init__()

2020-09-27 04:44 UTC, AtsushiSakai commented on PathPlanning/FlowField/flowfield.py
> +        draw_vertical_line(x, y, l, m_x, m_y, obs_dict, 'medium')
What do you mean the "medium" and "hard"? Could you please add comment to explain it in here or header comment?

2020-09-27 04:44 UTC, AtsushiSakai commented on PathPlanning/FlowField/flowfield.py
> +    flow_obj.find_path()
What is these color (yellow, green) meaning? Could you please add description to explain it.
![SS 2020-09-27 at 13 37 36](https://user-images.githubusercontent.com/3813847/94356272-6355ee80-00c7-11eb-9885-30256d496ffd.png)

2020-09-27 04:45 UTC, AtsushiSakai commented
One more thing, from the next PR. Could you please change branch for each PR? It is better for checking the git log in PR thread. You don't need to do anything in this PR.

2020-09-27 13:07 UTC, sarimmehdi commented
@AtsushiSakai I have made the requested changes. Please have a look.

2020-09-29 05:43 UTC, AtsushiSakai requested changes
Thank you for fixing. I have just one small comment. After fixing it, I will merge it.

2020-09-29 05:43 UTC, AtsushiSakai commented on PathPlanning/FlowField/flowfield.py
> +    # Some points are asigned a slightly higher energy value in the cost
asigned -> assigned ?

2020-09-29 05:51 UTC, sarimmehdi commented on PathPlanning/FlowField/flowfield.py
> +    # Some points are asigned a slightly higher energy value in the cost
I have made the change.

2020-09-29 06:32 UTC, AtsushiSakai approved these changes
LGTM. Thanks for your contribution!!

2020-09-29 06:32 UTC, merged