fixing sign in lane center calculation
AtsushiSakai/PythonRobotics pull request #435
Opened 2020-11-07 23:50 UTC by CtfChan

#### Reference issue

#### What does this implement/fix?

#### Additional information

2020-11-08 05:36 UTC, AtsushiSakai commented
Thank you for your PR. I checked this script, the` calc_lane_states` is so buggy. 
For example, when I set this configuration,
```
l_center = 10.0
l_heading = np.deg2rad(45.0)
l_width = 3.0
v_width = 1.0
d = 10
nxy = 5 
```
The terminal state should be, x =10, y =10.0, yaw = 45.0[deg], these input values should be global values.
So, the rotation matrix is not needed I think.

The result should be like
<img width="574" alt="SS 2020-11-08 at 14 35 22" src="https://user-images.githubusercontent.com/3813847/98458014-a9769580-21cf-11eb-9645-d61356b1e759.png">

Also, I found another bug. The nxy is the number of the path, so the number of the pass should be 5 in this example,
But there are 6 paths... Can you fix it also.

2020-11-08 05:38 UTC, AtsushiSakai requested changes
PTAL

2020-11-08 05:38 UTC, AtsushiSakai commented on PathPlanning/StateLatticePlanner/state_lattice_planner.py
>      yc = math.sin(l_heading) * d + math.cos(l_heading) * l_center
As i said this rotation is not needed. This line just should be
```
xc = d
yc = l_center
```

2020-11-08 05:44 UTC, AtsushiSakai commented
One more thing, could you please add this code in line 311 to remove animation result?

```
if show_animation:
   plt.close("all")

```

2020-11-08 18:40 UTC, CtfChan commented
> Thank you for your PR. I checked this script, the` calc_lane_states` is so buggy.
> For example, when I set this configuration,
> 
> ```
> l_center = 10.0
> l_heading = np.deg2rad(45.0)
> l_width = 3.0
> v_width = 1.0
> d = 10
> nxy = 5 
> ```
> 
> The terminal state should be, x =10, y =10.0, yaw = 45.0[deg], these input values should be global values.
> So, the rotation matrix is not needed I think.
> 
> The result should be like
> <img alt="SS 2020-11-08 at 14 35 22" width="574" src="https://user-images.githubusercontent.com/3813847/98458014-a9769580-21cf-11eb-9645-d61356b1e759.png">

Hi Atsushi,

I added the line to close the animations on 311.

I believe using the rotation matrix is required. Below is a link to another implementation of a state lattice planner that also uses the rotation matrix. 

https://github.com/enginBozkurt/MotionPlanner/blob/8f918944fd992b53e0c10b9e0df18f97a02b51b8/MotionPlannerCourse4FinalProject/local_planner.py#L139

Using the input values you gave I don't think the terminal state should be, x =10, y =10.0, yaw = 45.0[deg].  In the diagram below l_heading describes the rotation of frame b wrt to frame a. The centered terminal state (d, l_center) is wrt to frame b. So we need to rotate it back into frame a.

![](https://ctfchan.github.io/assets/lane_state_lattice.png)

Let me know what you think.


Cheers.

2020-12-04 13:41 UTC, AtsushiSakai commented
I think it depends on the input value on frame a or frame b in your fig. I think using frame a is usual for practical use case than using frame b. If we use frame a, we don't need to use a rotation matrix, I think. What do you think?

2020-12-10 18:00 UTC, CtfChan commented
Yes I agree. If you use frame A, you won't need frame B. But I think the shape parametrization p_{xx} used in the paper uses a frame A and B.

2020-12-20 04:52 UTC, AtsushiSakai commented
Hmm. I think shape parametrization p_{xx} does not depend on the frame.

2021-04-02 12:07 UTC, closed without merging