Clothoidal path planner
AtsushiSakai/PythonRobotics pull request #551
Opened 2021-10-14 02:23 UTC by daniel-s-ingram

Hi Atsushi, it's been a little while since my last PR, but I'm hoping to get more involved again! I'll add more detail to the PR soon.

Example outputs:
![clothoid](https://user-images.githubusercontent.com/17557934/137240364-fd24754f-a07d-4197-b41b-964f2af37693.gif)
![clothoid](https://user-images.githubusercontent.com/17557934/137240018-3a039b10-b688-4c75-a428-2e966a32a261.gif)
![clothoid](https://user-images.githubusercontent.com/17557934/137240464-a070b7e4-efc5-42bf-a4f1-b158d6c67487.gif)

2021-10-16 16:41 UTC, daniel-s-ingram commented
Latest commit allows for more possibilities like this:
![clothoid](https://user-images.githubusercontent.com/17557934/137595415-35ed4493-3321-43ef-ae9d-ccc2da62cb67.gif)

2021-10-16 17:26 UTC, daniel-s-ingram commented
@AtsushiSakai the six issues found in the `CodeFactor` check also exist in your master branch. Happy to fix them here, but I'm wondering why they're showing up as issues with this PR specifically.

2021-10-17 04:24 UTC, AtsushiSakai commented
Maybe that is CodeFactor's issue. So you can ignore these. I think I should remove CodeFacotor check soon.

2021-11-20 13:36 UTC, AtsushiSakai commented
Is it ready to review?

2021-11-21 13:33 UTC, daniel-s-ingram commented
Yes 👍

2021-11-26 01:35 UTC, AtsushiSakai requested changes
Sorry for waiting for review. I have some comments. PTAL.

2021-11-26 01:35 UTC, AtsushiSakai commented on PathPlanning/ClothoidalPaths/clothoidal_paths.py
> +"""
The directory name and script name should be `clothoidal_pathplanner`?

2021-11-26 01:35 UTC, AtsushiSakai commented on PathPlanning/ClothoidalPaths/clothoidal_paths.py
> +Clothoidal Path Planner
Could you please add a unit test file and documentation file based on this doc? :[How to contribute — PythonRobotics documentation](https://pythonrobotics.readthedocs.io/en/latest/how_to_contribute.html#adding-a-new-algorithm-example)

2021-11-26 01:35 UTC, AtsushiSakai commented on PathPlanning/ClothoidalPaths/clothoidal_paths.py
> +Reference paper: https://www.researchgate.net/publication/237062806
Could you please rebase this branch to master?

2021-11-26 01:35 UTC, AtsushiSakai commented on PathPlanning/ClothoidalPaths/clothoidal_paths.py
> +    num_clothoids=75,
This argument is no used?

2021-11-26 01:35 UTC, AtsushiSakai commented on PathPlanning/ClothoidalPaths/clothoidal_paths.py
> +    draw_clothoids(theta1_vals, theta2_vals, save_animation=False)
Could you please add `main()` function including these 3 lines and call it here?

2021-11-26 01:35 UTC, AtsushiSakai commented on PathPlanning/ClothoidalPaths/clothoidal_paths.py
> +def solve_for_root(theta1, theta2, delta):
Can you add docsting for each function to describe what the function is doing and each argument meanings.

2021-11-26 01:35 UTC, AtsushiSakai commented on PathPlanning/ClothoidalPaths/clothoidal_paths.py
> +Reference paper: https://www.researchgate.net/publication/237062806
```suggestion
Reference paper: Fast and accurate G1 fitting of clothoid curves https://www.researchgate.net/publication/237062806
```

2022-01-29 07:29 UTC, AtsushiSakai commented
@daniel-s-ingram Do you have time to finish this PR? If not, I can finish it, is it OK for you?

2022-02-06 13:18 UTC, AtsushiSakai commented
OK. Let's merge this. Then clean up in another PR. Thanks, @daniel-s-ingram.

2022-02-06 13:18 UTC, merged