Addition of velocity scale factor estimation to EKF
AtsushiSakai/PythonRobotics pull request #937
Opened 2023-11-19 08:13 UTC by rsasaki0109

#### What does this implement/fix?
I have added velocity scale factor estimation to the Extended Kalman filter

#### Additional information
I have adjusted the noise for velocity scale factor estimation, as it was not well-estimated with the default parameters.
It is assumed that the GNSS is RTK FIXed

#### CheckList
- [ ] Did you add an unittest for your new example or defect fix?
- [ ] Did you add documents for your new example?
- [ ] All CIs are green? (You can check it after submitting)

2023-11-20 12:03 UTC, AtsushiSakai commented
Hi, thank you for great PR!! 
Is it possible to add a new script for it, not modify the current file?

2023-11-20 12:33 UTC, rsasaki0109 commented
Thank you for your suggestion.
I've now added the new script `ekf_with_velocity_correction.py` to the `Localization/extended_kalman_filter` directory, which introduces the velocity correction feature for EKF.
Does this look good to you?

2023-12-03 13:19 UTC, AtsushiSakai commented
Thank you. Is it possible to update [this doc](https://github.com/AtsushiSakai/PythonRobotics/blob/master/docs/modules/localization/extended_kalman_filter_localization_files/extended_kalman_filter_localization_main.rst) to explain your code too?

2023-12-03 13:37 UTC, rsasaki0109 commented
OK, I will do that.

2023-12-03 20:22 UTC, rsasaki0109 commented
@AtsushiSakai 
I have added the document. Is this the correct way to add it?

2023-12-18 00:06 UTC, AtsushiSakai commented
I'm sorry for my late reply. @rsasaki0109 
For document, I think it is better to modify this file https://github.com/AtsushiSakai/PythonRobotics/blob/master/docs/modules/localization/extended_kalman_filter_localization_files/extended_kalman_filter_localization_main.rst
instead of adding new docs.

You can do grouping the "Filter design", "Motion model", "Observation model" for only position estimation and your position and velocity estimation.
https://github.com/AtsushiSakai/PythonRobotics/blob/master/docs/modules/localization/extended_kalman_filter_localization_files/extended_kalman_filter_localization_main.rst

2023-12-18 00:08 UTC, AtsushiSakai requested changes
Only remaining comment is for doc structure.

2024-01-07 11:58 UTC, AtsushiSakai commented
@rsasaki0109 Hi. Is it possible to finish this PR? Only remaining task is just organizing docs. If it is difficult for you, I can do it. Let me know. Thanks for good PR.

2024-01-11 11:32 UTC, rsasaki0109 commented
Sorry, I didn't notice your comment. I'll work on it when I have some free time.

2024-01-21 01:40 UTC, rsasaki0109 commented
@AtsushiSakai 
Is your comment meant to mean this?

- Motion Model
  - only position estimation
  - position and velocity estimation
 
- Observation model
  - only position estimation
  - position and velocity estimation

2024-01-21 01:44 UTC, AtsushiSakai commented
> Is your comment meant to mean this?
Yes. I think other two “filter design” and “Extended Kalman Filter” are common.

2024-01-21 13:03 UTC, AtsushiSakai commented
sorry, is it possible to merge the latest master code to build doc in CI?

2024-01-22 12:56 UTC, AtsushiSakai commented on docs/modules/localization/extended_kalman_filter_localization_files/extended_kalman_filter_localization_main.rst
> +Code: `PythonRobotics/extended_kalman_ekf_with_velocity_correctionfilter.py at master ﾂｷ
```suggestion
Code: `PythonRobotics/extended_kalman_ekf_with_velocity_correctionfilter.py
```

2024-01-22 13:02 UTC, merged

2024-01-22 20:42 UTC, rsasaki0109 commented
Thank you for your assistance! (I'm sorry, I've been a bit busy this month and my response was delayed...)